In [2]:
import numpy as np

In [4]:
import pandas as pd

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
df = pd.read_csv('data.csv')

In [15]:
df.head()

   sepallength  sepalwidth  petallength  peatlwidth           class
0          7.9         3.8          6.4         2.0  Iris-virginica
1          7.7         3.8          6.7         2.2  Iris-virginica
2          7.7         3.0          6.1         2.3  Iris-virginica
3          7.7         2.8          6.7         2.0  Iris-virginica
4          7.7         2.6          6.9         2.3  Iris-virginica

In [18]:
x = df.iloc[:,:-1]

In [19]:
x

    sepallength  sepalwidth  petallength  peatlwidth
0           7.9         3.8          6.4         2.0
1           7.7         3.8          6.7         2.2
2           7.7         3.0          6.1         2.3
3           7.7         2.8          6.7         2.0
4           7.7         2.6          6.9         2.3
..          ...         ...          ...         ...
62          4.5         2.3          1.3         0.3
63          4.4         3.2          1.3         0.2
64          4.4         3.0          1.3         0.2
65          4.4         2.9          1.4         0.2
66          4.3         3.0          1.1         0.1

[67 rows x 4 columns]