In [1]:
import pandas as pd

In [6]:
s = pd.Series([34,56,7,87,98,97,76,45,67])#this is the method of pandas which arrange the numbers in series 
s

0    34
1    56
2     7
3    87
4    98
5    97
6    76
7    45
8    67
dtype: int64

In [7]:
type(s)

pandas.core.series.Series

In [9]:
#by using this indexing method we can set our own index of the values 
s = pd.Series([34,56,7,87,98,97],index = ['monu','shubh','simran','himesh','rudransh','aloosingh'])
s

monu         34
shubh        56
simran        7
himesh       87
rudransh     98
aloosingh    97
dtype: int64

In [12]:
s['monu']#by doing this we can get the certain value at certain index

np.int64(34)

In [11]:
int(s['himesh'])

87

In [19]:
#data frame is the method of the pandas which is like a dictonary which contains many seiries 
data = {
"name": ["Monu verma", "Bob", "Charlie"],
"age": [17, 30, 35],
"city": ["haryana--Faridabad", "Mumbai", "Bangalore"]
}
d = pd.DataFrame(data)
d

         name  age                city
0  Monu verma   17  haryana--Faridabad
1         Bob   30              Mumbai
2     Charlie   35           Bangalore

In [20]:
d.columns

Index(['name', 'age', 'city'], dtype='object')

In [21]:
d.index

RangeIndex(start=0, stop=3, step=1)

In [25]:
d.index = [1,2,3]

In [26]:
d.index

Index([1, 2, 3], dtype='int64')

In [27]:
d

         name  age                city
1  Monu verma   17  haryana--Faridabad
2         Bob   30              Mumbai
3     Charlie   35           Bangalore

In [28]:
d.var

<bound method DataFrame.var of          name  age                city
1  Monu verma   17  haryana--Faridabad
2         Bob   30              Mumbai
3     Charlie   35           Bangalore>

In [29]:
d

         name  age                city
1  Monu verma   17  haryana--Faridabad
2         Bob   30              Mumbai
3     Charlie   35           Bangalore

In [30]:
d.index

Index([1, 2, 3], dtype='int64')

In [31]:
d.columns

Index(['name', 'age', 'city'], dtype='object')

In [33]:
d.columns  = ['Name','Age','City']

In [34]:
d

         Name  Age                City
1  Monu verma   17  haryana--Faridabad
2         Bob   30              Mumbai
3     Charlie   35           Bangalore