In [1]:
import pandas as pd

In [2]:
marks = [['monu',7],['Chiku',88],['silky',99],['leyland',69],['gabimaru',100]]

In [3]:
marks

[['monu', 7], ['Chiku', 88], ['silky', 99], ['leyland', 69], ['gabimaru', 100]]

In [13]:
a=pd.DataFrame(marks,columns= ["Name","marks"]) #this is the way to add columns to the lists of list

In [14]:
a

       Name  marks
0      monu      7
1     Chiku     88
2     silky     99
3   leyland     69
4  gabimaru    100

In [15]:
a.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
a.index= [1,2,3,4,5]

In [17]:
a

       Name  marks
1      monu      7
2     Chiku     88
3     silky     99
4   leyland     69
5  gabimaru    100

In [18]:
a.columns

Index(['Name', 'marks'], dtype='object')

In [27]:
#method of panda for making the DataFrames using the python dictionary
data = {"a":[1,2,3],"b":[2,3,4]}
data

{'a': [1, 2, 3], 'b': [2, 3, 4]}

In [28]:
df = pd.DataFrame(data)

In [29]:
df

   a  b
0  1  2
1  2  3
2  3  4

In [30]:
df.index = ['1).' , '2).' , '3).']

In [31]:
df

     a  b
1).  1  2
2).  2  3
3).  3  4

In [40]:
#making a DataFrame using the numpy arrays 
import numpy as np 
array = np.array([[1,2],[3,4]])
array

array([[1, 2],
       [3, 4]])

In [41]:
df = pd.DataFrame(array)

In [42]:
df

   0  1
0  1  2
1  3  4

In [43]:
df.index = ["a","b"]

In [44]:
df

   0  1
a  1  2
b  3  4

In [48]:
df.columns = ["NUMBERS--1","NUMBERS--2"]

In [49]:
df

   NUMBERS--1  NUMBERS--2
a           1           2
b           3           4

In [59]:
#this is a way to read the data of excel file inn panda data frames 
pd.read_excel('data.xlsx')

      name  School   marks
0  shubham       os       1
1    joshua      sk       2
2      jack     sh'       3
3      alex      hf       4
4    roshan       d       5
5     rishi     sh'       6
6   aaskash     sh'       6

In [60]:
#this is the way to read the data in panda of json file 
pd.read_json('data.json')

   name language
0  monu   python
1    ka      NaN

In [62]:
#this is a way to get the data in panda framework from the url csv file 
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [85]:
df.head()#it is the method for analyzing the data of top 5 columns in the data to analyize the pattern

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [86]:
df.tail()#it is the method for checking the last 5 coloums of the data for analyzing the data

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [87]:
df.info()#it is a method for checking the information of the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [88]:
df.describe()# it is a method for checking the description of the data in the sense like total values or average and min or mx

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [89]:
df.index#method for checking the index of the DATAFRAMEWORK

RangeIndex(start=0, stop=244, step=1)

In [90]:
df.columns#it is a method for checking the columns of the data

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')