In [1]:
import pandas as  pd

In [2]:
df = pd.read_csv('deta.csv')
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [3]:
df.isnull()#this is the method which tell either data has null data or not following the true and false

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [4]:
df.isnull().sum()#this shows the number of null in the colums..sum function

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [5]:
df.dropna()#this is the method which help in producing the clean data 
#the data without the null data

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [6]:
df.dropna(axis=1)#it remove the whole column even there is only one missing value

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [7]:
df.fillna('-')#it is method which fill the place with nan value every nan which is present in the data 
#but it only make the copy of the data not changing the original data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie     -        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie     -        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        -  28.0        Delhi      F     eve@domain.com           -
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie     -        Delhi      M    charlie@example  20-07-2021

In [8]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [9]:
df["Age"].fillna(df["Age"].mean())#it fill  the nan places with the mean of all the data as total

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [10]:
df.fillna(method = "ffill")#this is the method which fills the nan places with  the previoys values

C:\Users\sec\AppData\Local\Temp\ipykernel_10320\1422472483.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")#this is the method which fills the nan places with  the previoys values

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [11]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [12]:
df.fillna(method = 'bfill')

C:\Users\sec\AppData\Local\Temp\ipykernel_10320\3673297803.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'bfill')

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [13]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [14]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [15]:
df.ffill

<bound method NDFrame.ffill of       Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021>

In [16]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [17]:
df.duplicated()#method for indentifying the duplicated

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [18]:
df.drop_duplicates()#it drops the duplicate

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [19]:
df.duplicated(subset=["Name","Age"])#it tell if it is not a unqiue pari or not

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [20]:
df['Name'].str.lower()#string function in pandas

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [21]:
df["City"].str.contains("delhi",case = False)#it returns pandas series.

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [22]:
df["Email"].str.split("@")#to remove common things from a coulumn split method is used for that function

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [23]:
df2 = df.dropna().copy()

In [24]:
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [25]:
df3  = df2
df3["Age"] = df3["Age"].astype(int).copy()
df3

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [26]:

df3.info

<bound method DataFrame.info of     Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021>

In [27]:
df3

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [28]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [29]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [30]:
df3

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [31]:
df3["Age group"] = df3['Age'].apply(lambda x :"adult" if x >= 18 else "Minor")#apply is a function of pandas which help in 
#making a columns within putting condions
df3

    Name  Age         City Gender              Email   Join Date Age group
0  Alice   25     New York      F  alice@example.com  01-05-2021     adult
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     adult
4  David   22       Mumbai      M  david@example.com  12-11-2019     adult
6  Alice   25     New York      F  alice@example.com  01-05-2021     adult
7  Alice   25     New York      F  alice@example.com  01-05-2021     adult

In [32]:
gender_defined = {"M":"Male","F":"Female","O":"Other"}
df3["Gender"] = df3["Gender"].map(gender_defined)
df3

    Name  Age         City  Gender              Email   Join Date Age group
0  Alice   25     New York  Female  alice@example.com  01-05-2021     adult
2    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     adult
4  David   22       Mumbai    Male  david@example.com  12-11-2019     adult
6  Alice   25     New York  Female  alice@example.com  01-05-2021     adult
7  Alice   25     New York  Female  alice@example.com  01-05-2021     adult

In [35]:
df3["City"] = df3["City"].replace({"New York":"NEW_YORK"})
df3

    Name  Age         City  Gender              Email   Join Date Age group
0  Alice   25     NEW_YORK  Female  alice@example.com  01-05-2021     adult
2    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     adult
4  David   22       Mumbai    Male  david@example.com  12-11-2019     adult
6  Alice   25     NEW_YORK  Female  alice@example.com  01-05-2021     adult
7  Alice   25     NEW_YORK  Female  alice@example.com  01-05-2021     adult