In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [3]:
#for sorting the numbers 
df.sort_values("Year",ascending = False)#using false statement for the gettingthe decreadsed oreder data

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [4]:
#using the normal sorting methode 
df2 = df.sort_values(["IMDb",'Year']).copy()#position of the condition you are giving also matter if you  give some condition better then other than it is going to be considered
#postion matter

In [5]:
df2#now problem is that it is showing that indexing is not lloking good in the sense you know what i am saying here

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
7,Hrithik Roshan,War,2019,Action,475,6.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [6]:
#reseting the index to make it in right pattern
df2.reset_index(drop= True,inplace = True)#using the drop = True so it is  not going to show the old index which it was showing recentily when we were seeing when we rnnded the fucntion recentioly

In [7]:
#using inplace = True is a method update the orgiginal data it applies in most of the function in pandas
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
3,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Hrithik Roshan,War,2019,Action,475,6.5
5,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
8,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
9,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
10,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [8]:
df2.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
3,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Hrithik Roshan,War,2019,Action,475,6.5
5,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
8,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
9,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
10,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [9]:
#here rank make a new column and rank the imdb as bigger it is it will get bigger rank but if you will use the False methode it is going to give you opposite value and method dense help giving the integer rank 
df2["rank"] = df2["IMDb"].rank(ascending= False,method= 'dense')

In [10]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,rank
0,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
3,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
4,Hrithik Roshan,War,2019,Action,475,6.5,7.0
5,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
6,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
7,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
8,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
9,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
10,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0

In [12]:
df = df[["Genre","Actor","Year","IMDb","Film","BoxOffice(INR Crore)"]]
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,rank
0,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
3,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
4,Hrithik Roshan,War,2019,Action,475,6.5,7.0
5,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
6,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
7,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
8,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
9,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
10,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0

In [15]:
col = ["Actor"]+[col for col in df.columns if col != "Actor"]
df = df[col]
df

,Actor,Genre,Year,IMDb,Film,BoxOffice(INR Crore)
0,Shah Rukh Khan,Action,2023,7.2,Pathaan,1050
1,Salman Khan,Action,2017,6.0,Tiger Zinda Hai,565
2,Aamir Khan,Biography,2016,8.4,Dangal,2024
3,Ranbir Kapoor,Fantasy,2022,5.6,Brahmastra,431
4,Ranveer Singh,Historical,2018,7.0,Padmaavat,585
5,Ayushmann Khurrana,Thriller,2018,8.3,Andhadhun,111
6,Rajkummar Rao,Horror Comedy,2018,7.5,Stree,180
7,Hrithik Roshan,Action,2019,6.5,War,475
8,Akshay Kumar,Comedy,2019,7.0,Good Newwz,318
9,Kartik Aaryan,Horror Comedy,2022,5.9,Bhool Bhulaiyaa 2,266
10,Varun Dhawan,Romantic Comedy,2017,6.1,Badrinath Ki Dulhania,201
11,Vicky Kaushal,Action,2019,8.2,Uri: The Surgical Strike,342