In [1]:
#in this file we are going to filter the data

In [7]:
import pandas as pd 
df = pd.read_csv('data.csv')
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [9]:
df['Actor']#this is a way of calling a column from a data

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [39]:
#this is the some methods of selection in pandas 
df[['Actor','IMDb']]#it is a way to generate multiple column thing to remember is 2 boxes

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [40]:
df.loc[0]#is is the way to get the inof or everycolumns details about the index number

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [41]:
df.loc[8,"Genre"]#this is a way to get the precise info about the Data in this

'Comedy'

In [42]:
df.iloc[8,3]#this is a way to get the precise info about the data but in the way that columns also becomes index

'Comedy'

In [43]:
df.loc[0:2,['Actor','IMDb']]#this is method to use slicing with loc method

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0
2      Aamir Khan   8.4

In [44]:
#in i-loc index are exclusive and in loc it is inclusive because it is desigined that way

In [45]:
df.loc[0,'Actor']

'Shah Rukh Khan'

In [46]:
df.at[0,'Actor']#it is made for accessing a particular thing in the data  loc can do this thing too but at and iat is maded exclusively for this

'Shah Rukh Khan'

In [47]:
df.iat[0,0]

'Shah Rukh Khan'

In [38]:
#filtering methods in pandas

In [55]:
df[df['IMDb']>8]#this is the method of filtering the numbers greater or lesser

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [59]:
df[(df['IMDb']>6)&(df['Year']>2020)]#this is a method of filtering which is used to more than one filtering at a same time

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [71]:
df.query("Year>2019 and IMDb>6")#query is pandas method it is very minimal and is useful

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [82]:
df2 = df[['Actor','Genre']].copy()

In [83]:
df2

                 Actor            Genre
0       Shah Rukh Khan           Action
1          Salman Khan           Action
2           Aamir Khan        Biography
3        Ranbir Kapoor          Fantasy
4        Ranveer Singh       Historical
5   Ayushmann Khurrana         Thriller
6        Rajkummar Rao    Horror Comedy
7       Hrithik Roshan           Action
8         Akshay Kumar           Comedy
9        Kartik Aaryan    Horror Comedy
10        Varun Dhawan  Romantic Comedy
11       Vicky Kaushal           Action

In [84]:
df2

                 Actor            Genre
0       Shah Rukh Khan           Action
1          Salman Khan           Action
2           Aamir Khan        Biography
3        Ranbir Kapoor          Fantasy
4        Ranveer Singh       Historical
5   Ayushmann Khurrana         Thriller
6        Rajkummar Rao    Horror Comedy
7       Hrithik Roshan           Action
8         Akshay Kumar           Comedy
9        Kartik Aaryan    Horror Comedy
10        Varun Dhawan  Romantic Comedy
11       Vicky Kaushal           Action

In [81]:
#always use copy method if you want to chang or want to make anther data that's it

In [87]:
df2.loc[0,'Actor'] = 'salu bhai'

In [88]:
df2

                 Actor            Genre
0            salu bhai           Action
1          Salman Khan           Action
2           Aamir Khan        Biography
3        Ranbir Kapoor          Fantasy
4        Ranveer Singh       Historical
5   Ayushmann Khurrana         Thriller
6        Rajkummar Rao    Horror Comedy
7       Hrithik Roshan           Action
8         Akshay Kumar           Comedy
9        Kartik Aaryan    Horror Comedy
10        Varun Dhawan  Romantic Comedy
11       Vicky Kaushal           Action

In [89]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2