In [1]:
import pandas as pd

In [3]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})
 
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [4]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [5]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [7]:
pd.merge(employees,departments,on='DeptID')#this is method used for merging the two data's
#it is called inner join method

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [9]:
pd.merge(employees,departments,how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [17]:
pd.merge(employees,departments, how="right")#this is the method which give every value of the right side and give nana in the missing places value

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [18]:
pd.merge(employees,departments,how="outer")#it is used for getting everyt output you can get out of the merged table 
#it give nan in the missing places

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [48]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"],
                   "age":[22,12]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"],
                   "score":[22,45]})
df1

    Name  age
0  Alice   22
1    Bob   12

In [49]:
df2
pd.concat([df1,df2])#this is the method for cancatting the data frames means it is used for the overlaping the data frames
#limits columns names should be same in this

      Name   age  score
0    Alice  22.0    NaN
1      Bob  12.0    NaN
0  Charlie   NaN   22.0
1    David   NaN   45.0

In [50]:
pd.concat([df1,df2])

      Name   age  score
0    Alice  22.0    NaN
1      Bob  12.0    NaN
0  Charlie   NaN   22.0
1    David   NaN   45.0

In [52]:
pd.concat([df1,df2],axis=1)#this method also help in cleaning the nan not a number situation

    Name  age     Name  score
0  Alice   22  Charlie     22
1    Bob   12    David     45