In [8]:
import pandas as pd

# Sample DataFrame
data = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Math': [85, 78, 92],
'Science': [90, 82, 89],
'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [21]:
#df melt is a method in which we can change or reshsape the entire data in differeent ways
dd = df.melt(id_vars = ['Name'] , value_vars = ['English','Math','Science'],var_name = 'Subjects',value_name = 'Score')
dd

      Name Subjects  Score
0    Alice  English     88
1      Bob  English     85
2  Charlie  English     94
3    Alice     Math     85
4      Bob     Math     78
5  Charlie     Math     92
6    Alice  Science     90
7      Bob  Science     82
8  Charlie  Science     89

In [16]:
#pivot is a method is just uno reverse action of the melt function it brings back the data to wide format from the long format

In [20]:
dd.pivot_table(index="Name", columns="Subjects",values="Score", aggfunc="mean")#have to use aggfunc in order to avoid the error because you cant have two same subject in this case with alice so yeah we have to use the agg func methode

Subjects  English  Math  Science
Name
Alice        88.0  85.0     90.0
Bob          85.0  78.0     82.0
Charlie      94.0  92.0     89.0